services:
  db:
    image: postgres:15
    container_name: hotel_db_container
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.20
    container_name: hotel_liquibase_container
    volumes:
      - ./liquibase:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog-master.xml
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/hotel_db
      LIQUIBASE_COMMAND_USERNAME: admin
      LIQUIBASE_COMMAND_PASSWORD: password123
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command: update
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: